name: Grab Tesst7 M3U8

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # tiap jam

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run grabber
        run: python Autorotate.py

      - name: Push output
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase origin master
          git add TESSTSS7.m3u8
          git commit -m "auto: update TESSTSS7.m3u8" || echo "no changes"
          git push
