name: Grab OMRRI M3U8

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Setiap 2 jam

jobs:
  fetch_rri:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install playwright python-dotenv
          playwright install chromium

      - name: Jalankan get_rri.py
        run: python get_rri.py

      - name: Commit & Push Hasil
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add RRILIVE.m3u8
          git commit -m "Update RRILIVE.m3u8 - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
