name: Ekstrak & Commit DOOR UTTUT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Setiap 1 jam

jobs:
  extract:
    runs-on: ubuntu-latest
    env:
      PROXY_SKIDDLE: ${{ secrets.PROXY_SKIDDLE }}
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Jalankan skrip ekstraksi proxy
        run: python3 uttut_cheker2.py

      - name: Commit dan Push hasil
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add UTTUT2_DOOR.txt UTTUTHONGKONG_DOOR.txt UTTUTSINGAPORE_DOOR.txt
          git commit -m "🔁 Update UTTUT otomatis" || echo "Tidak ada perubahan"
          git push
