name: Update trans7.m3u8

on:
  schedule:
    - cron: "0 * * * *"  # Setiap jam
  workflow_dispatch:

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests

      - name: Jalankan script Python
        run: |
          python3 scriptdaily.py "" https://www.dailymotion.com/video/x8qckyq

      - name: Debug: cek file trans7.m3u8
        run: |
          ls -lah
          cat trans7.m3u8 || echo "File trans7.m3u8 belum ada"

      - name: Commit hasil trans7.m3u8
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          if [ -f "trans7.m3u8" ]; then
            echo "✅ File trans7.m3u8 ditemukan, siap commit."
            git add trans7.m3u8
            git commit -m "Update trans7.m3u8 [auto]" || echo "ℹ️ Tidak ada perubahan untuk di-commit."
            git push
          else
            echo "⚠️ File trans7.m3u8 TIDAK ditemukan, skip commit."
          fi
