name: Update trans7.m3u8

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: |
          python3 -m pip install requests

      - name: Run script
        run: |
          python3 scriptdaily.py "" https://www.dailymotion.com/video/x8qckyq

       - name: Commit m3u8 file
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          if [ -f "trans7.m3u8" ]; then
            git add trans7.m3u8
            git commit -m "Update trans7.m3u8 [auto]" || echo "No changes to commit"
            git push
          else
            echo "File trans7.m3u8 not found, skipping commit."
          fi
