name: Fetch Dailymotion M3U8

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Setiap hari jam 08:00 WIB

jobs:
  grab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          VIDEO_URL: https://www.dailymotion.com/video/x8qckyq  # Ganti sesuai kebutuhan
          OUTPUT_FILE: trans7.m3u8
          PROXY: ""
        run: |
          python3 scriptdaily.py

      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add trans7.m3u8
          git commit -m "Update M3U8 - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
