name: Dailymotion M3U8 Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # jalan setiap jam

jobs:
  fetch-hls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run proxy checker
        run: python3 proxy_checker.py || echo "proxy_checker error diabaikan"

      - name: Run Dailymotion HLS fetcher
        run: |
          PROXY=$(cat valid_proxy.txt || echo "")
          echo "Using proxy: $PROXY"
          python3 scriptdaily.py "$PROXY" "https://www.dailymotion.com/video/x8qckyq" "trans7.m3u8"

      - name: Commit and Push result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trans7.m3u8
          git commit -m "✅ Update trans7.m3u8 [auto]" || echo "No changes to commit"
          git push
